# Generated by Django 5.1.3 on 2024-11-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
            ],
        ),
    ]
